// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcLEig21SAAgp_l98mIpYvBOFXkCP3Z20',
    appId: '1:623906779506:web:2f7fc2f37f02ac2ba52deb',
    messagingSenderId: '623906779506',
    projectId: 'sgk-home',
    authDomain: 'sgk-home.firebaseapp.com',
    storageBucket: 'sgk-home.firebasestorage.app',
    measurementId: 'G-JV973PN6LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX7WhRXy09q0x8uGR3STEJ4XgTEcq7NIE',
    appId: '1:623906779506:android:25c3875728d2a668a52deb',
    messagingSenderId: '623906779506',
    projectId: 'sgk-home',
    storageBucket: 'sgk-home.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcrJifIBgmqVxBDdW5YJFgJbMx0V3eZzo',
    appId: '1:623906779506:ios:cb47be0b09793a96a52deb',
    messagingSenderId: '623906779506',
    projectId: 'sgk-home',
    storageBucket: 'sgk-home.firebasestorage.app',
    iosBundleId: 'com.example.appRenseignement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcrJifIBgmqVxBDdW5YJFgJbMx0V3eZzo',
    appId: '1:623906779506:ios:cb47be0b09793a96a52deb',
    messagingSenderId: '623906779506',
    projectId: 'sgk-home',
    storageBucket: 'sgk-home.firebasestorage.app',
    iosBundleId: 'com.example.appRenseignement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcLEig21SAAgp_l98mIpYvBOFXkCP3Z20',
    appId: '1:623906779506:web:e73b2a8877aa9146a52deb',
    messagingSenderId: '623906779506',
    projectId: 'sgk-home',
    authDomain: 'sgk-home.firebaseapp.com',
    storageBucket: 'sgk-home.firebasestorage.app',
    measurementId: 'G-M1F9Y8H3WT',
  );

}